'use strict';
(() => {
 const $=id=>document.getElementById(id), audio=$('audio');
 const NS='taliesin-v3', CACHE=NS+'-encrypted-audio', DB=NS+'-device', AAD='Taliesin:v2:';
 const state={catalog:null,tracks:[],index:0,key:null,keys:{},loading:false,token:0,current:null,next:null,positions:{},filter:'all',saved:new Set(),saving:false,cancel:null,saveTimer:0,prefetching:null};
 let toastTimer,seekTimer,seekDelay,holding=false,holdButton=null;
 const encode=s=>new TextEncoder().encode(s);
 const fmt=n=>{n=Math.max(0,Math.floor(Number(n)||0));return n>=3600?`${Math.floor(n/3600)}:${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`:`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;};
 const bytes=n=>`${((n||0)/1e6).toFixed(1)} MB`;
 const b64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'=')),c=>c.charCodeAt(0));
 const hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
 const track=()=>state.tracks[state.index];
 // Independent chapter keys v5. The earlier key remains in its original slot.
 const keyFor=t=>t?state.keys[t.key_id||'legacy']:null;
 async function restoreKeys(){try{state.keys=(await setting('keys-v5'))||{};const old=await setting('key');if(old)state.keys.legacy=old;}catch{}state.key=Object.values(state.keys)[0]||null;}
 function chooseUnlocked(preferred){const at=state.tracks.findIndex(t=>t.id===preferred&&keyFor(t));if(at>=0)state.index=at;else if(!keyFor(track())){const first=state.tracks.findIndex(t=>keyFor(t));if(first>=0)state.index=first;}}

 const toast=text=>{clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500);};
 function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
 function controlState(){const usable=!!(keyFor(track())&&track()&&state.current&&!state.loading);['play','seek','rewind','forward','restartChapter','downloadCurrent'].forEach(id=>$(id).disabled=!usable);$('previous').disabled=!state.key||state.loading||state.index===0;$('next').disabled=!state.key||state.loading||state.index>=state.tracks.length-1;$('saveCurrent').disabled=!state.key||!track();$('saveAll').disabled=!state.key||!state.tracks.length||state.saving;}
 function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('settings');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
 async function setting(name,value,remove=false){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('settings',value===undefined&&!remove?'readonly':'readwrite');const os=tx.objectStore('settings');const req=remove?os.delete(name):value===undefined?os.get(name):os.put(value,name);let result;req.onsuccess=()=>{result=req.result;};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};});}
 function savePosition(force=false){if(!track()||!state.current||state.loading)return;if(!force&&Date.now()-state.saveTimer<2500)return;state.saveTimer=Date.now();state.positions[track().id]=Math.min(audio.currentTime||0,track().duration);try{localStorage.setItem(NS+'-progress',JSON.stringify({last:track().id,positions:state.positions}));}catch{}}
 function updateTime(){const t=track();if(!t)return;const duration=Number.isFinite(audio.duration)?audio.duration:t.duration;const now=audio.currentTime||0;if(document.activeElement!==$('seek'))$('seek').value=String(now);$('seek').max=String(duration);$('elapsed').textContent=fmt(now);$('remaining').textContent='−'+fmt(Math.max(0,duration-now));let before=0;for(let i=0;i<state.index;i++)before+=state.tracks[i].duration;const total=state.catalog.total_duration||state.tracks.reduce((n,x)=>n+x.duration,0);$('wholeProgress').textContent=`${fmt(before+now)} of ${fmt(total)} · ${Math.min(100,Math.round((before+now)/total*100))}% through ${state.catalog.complete===false?'available chapters':'the book'}`;if(navigator.mediaSession&&duration>0){try{navigator.mediaSession.setPositionState({duration,playbackRate:1,position:Math.max(0,Math.min(now,duration))});}catch{}}}
 function updatePlay(){const playing=!audio.paused&&!audio.ended;$('playSymbol').textContent=playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',playing?'Pause':'Play');if(navigator.mediaSession)navigator.mediaSession.playbackState=playing?'playing':'paused';}
 function setMetadata(){const t=track();if(!t)return;$('partName').textContent=t.book?`Part ${t.book} · ${t.part}`:'The Pendragon Cycle · Book one';$('chapterTitle').textContent=t.title;$('saveCurrent').textContent=state.saved.has(t.id)?'Saved offline ✓':'Save offline ↓';if(navigator.mediaSession&&window.MediaMetadata){navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:'Stephen Lawhead',album:`Taliesin · ${t.part}`,artwork:[{src:new URL('icon-512.png',location.href).href,sizes:'512x512',type:'image/png'}]});}renderList();}
 function urlFor(t){const u=new URL(t.src,location.href);if(u.origin!==location.origin||!u.pathname.startsWith(new URL('./',location.href).pathname+'audio-v2/'))throw new Error('Unsafe audio path in catalog.');return u.href;}
 async function encrypted(t,progress,signal){const url=urlFor(t);let cache;try{cache=await caches.open(CACHE);const hit=await cache.match(url);if(hit)return new Uint8Array(await hit.arrayBuffer());}catch{}
  // Verified transport chunks v3
  if(Array.isArray(t.chunks)){
   if(!Number.isSafeInteger(t.bytes)||t.bytes<28||t.bytes>100000000||!t.chunks.length||t.chunks.length>100)throw new Error('Invalid chapter chunk manifest.');
   if(t.chunks.reduce((n,p)=>n+p.bytes,0)!==t.bytes)throw new Error('Chapter chunk sizes do not add up.');
   const joined=new Uint8Array(t.bytes);let offset=0,pieceCache;
   try{pieceCache=await caches.open(CACHE+'-pieces');}catch{}
   for(const part of t.chunks){
    if(signal?.aborted)throw new DOMException('Cancelled','AbortError');
    if(!Number.isSafeInteger(part.bytes)||part.bytes<1||part.bytes>4000000||!/^[a-f0-9]{64}$/.test(part.sha256))throw new Error('Invalid audio piece.');
    const pieceURL=urlFor(part);let raw;
    if(pieceCache){const hit=await pieceCache.match(pieceURL);if(hit){raw=new Uint8Array(await hit.arrayBuffer());if(raw.length!==part.bytes||hex(await crypto.subtle.digest('SHA-256',raw))!==part.sha256){await pieceCache.delete(pieceURL);raw=null;}}}
    if(!raw){
     const response=await fetch(pieceURL,{signal});if(!response.ok)throw new Error(`Audio piece could not be loaded (${response.status}). Retry to resume.`);
     // HTTP compression can make Content-Length exceed the decoded piece size. The bounded reader and SHA-256 below validate the actual bytes.
     if(response.body?.getReader){const reader=response.body.getReader();raw=new Uint8Array(part.bytes);let used=0;try{for(;;){const {done,value}=await reader.read();if(done)break;if(used+value.length>part.bytes){await reader.cancel();throw new Error('Audio piece is larger than expected.');}raw.set(value,used);used+=value.length;if(progress)progress(offset+used,t.bytes);}if(used!==part.bytes)throw new Error('Incomplete audio piece. Retry to resume.');}finally{reader.releaseLock();}}
     else raw=new Uint8Array(await response.arrayBuffer());
     if(raw.length!==part.bytes||hex(await crypto.subtle.digest('SHA-256',raw))!==part.sha256)throw new Error('Audio piece failed its integrity check. Retry to resume.');
     try{if(pieceCache)await pieceCache.put(pieceURL,new Response(raw,{headers:{'Content-Type':'application/octet-stream'}}));}catch{}
    }
    joined.set(raw,offset);offset+=raw.length;if(progress)progress(offset,t.bytes);
   }
   if(hex(await crypto.subtle.digest('SHA-256',joined))!==t.sha256)throw new Error('Reassembled chapter failed its integrity check.');
   return joined;
  }
  const res=await fetch(url,{signal});if(!res.ok)throw new Error(res.status===404?'This chapter has not reached the server yet. Try again.':`Audio request failed (${res.status}).`);
  const expected=t.bytes;let raw;if(res.body&&res.body.getReader){const reader=res.body.getReader(),chunks=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;chunks.push(value);size+=value.length;if(size>expected+1024)throw new Error('Chapter file is larger than expected.');if(progress)progress(size,expected);}}finally{reader.releaseLock();}raw=new Uint8Array(size);let p=0;for(const chunk of chunks){raw.set(chunk,p);p+=chunk.length;}}else raw=new Uint8Array(await res.arrayBuffer());
  return raw;
 }
 async function verify(t,raw){if(raw.byteLength!==t.bytes||hex(await crypto.subtle.digest('SHA-256',raw))!==t.sha256){try{const c=await caches.open(CACHE);await c.delete(urlFor(t));}catch{}state.saved.delete(t.id);throw new Error('Chapter integrity check failed. Retry to fetch a clean copy.');}}
 async function openTrack(t,progress){const raw=await encrypted(t,progress);await verify(t,raw);const chapterKey=keyFor(t);if(!chapterKey){$('unlockPanel').hidden=false;throw new Error('This chapter needs its private listening link. Earlier recordings keep their earlier unlock code.');}let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:raw.slice(0,12),additionalData:encode(AAD+t.id)},chapterKey,raw.slice(12));}catch{throw new Error('This code does not unlock the chapter. Use the latest private listening link.');}const blob=new Blob([plain],{type:'audio/mpeg'});return {id:t.id,blob,url:URL.createObjectURL(blob)};}
 function release(item){if(item)URL.revokeObjectURL(item.url);}
 async function prefetch(){const t=state.tracks[state.index+1];if(!t||!state.key||state.next?.id===t.id||state.prefetching===t.id)return;const token=state.token;state.prefetching=t.id;try{const item=await openTrack(t);if(state.token!==token||!state.key){release(item);return;}release(state.next);state.next=item;}catch{/* Current playback stays available; the next chapter can be retried on demand. */}finally{if(state.prefetching===t.id)state.prefetching=null;}}
 async function load(index,autoplay=false,position){if(index<0||index>=state.tracks.length||!state.key)return;savePosition(true);audio.pause();const token=++state.token;state.loading=true;state.index=index;setMetadata();controlState();status('Loading chapter…');let item;
  try{const t=track();if(state.next?.id===t.id){item=state.next;state.next=null;}else item=await openTrack(t,(got,total)=>{if(state.token===token)status(`Loading chapter · ${Math.min(100,Math.round(got/total*100))}%`);});if(token!==state.token){release(item);return;}const old=state.current;state.current=item;audio.src=item.url;audio.playbackRate=1;audio.defaultPlaybackRate=1;
   const wanted=position===undefined?(state.positions[t.id]||0):position;
   await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>finish(new Error('Audio did not become ready. Tap the chapter to retry.')),25000);const finish=e=>{clearTimeout(timeout);audio.removeEventListener('loadedmetadata',ready);audio.removeEventListener('error',fail);e?reject(e):resolve();};const ready=()=>{if(token!==state.token){finish();return;}audio.currentTime=Math.max(0,Math.min(wanted>=t.duration-1?0:wanted,Math.max(0,audio.duration-.2)));finish();};const fail=()=>finish(new Error('Safari could not open this audio file.'));audio.addEventListener('loadedmetadata',ready);audio.addEventListener('error',fail);audio.load();});release(old);if(token!==state.token)return;state.loading=false;controlState();updateTime();status(state.saved.has(t.id)?'Saved on this device.':'Ready to listen.');if(autoplay)await play();prefetch();
  }catch(e){if(token!==state.token)return;state.loading=false;status(e.message||'Unable to load audio. Check your connection and retry.',true);controlState();}
 }
 async function play(){if(!state.current||state.loading)return;try{audio.playbackRate=1;await audio.play();status(state.saved.has(track().id)?'Playing · saved offline':'Playing');prefetch();}catch(e){status(e.name==='NotAllowedError'?'Tap Play to start this chapter.':'Playback could not start. Tap the chapter to retry.',true);}updatePlay();}
 function seek(delta){if(!state.current||state.loading)return;const max=Number.isFinite(audio.duration)?audio.duration:track().duration;audio.currentTime=Math.max(0,Math.min(max-.05,audio.currentTime+delta));updateTime();savePosition(true);}
 function endHold(){clearTimeout(seekDelay);clearInterval(seekTimer);if(holdButton)holdButton.classList.remove('holding');holdButton=null;holding=false;}
 function hold(id,direction){const b=$(id);b.addEventListener('contextmenu',e=>e.preventDefault());b.addEventListener('pointerdown',e=>{if(b.disabled||e.button>0)return;e.preventDefault();endHold();holding=true;holdButton=b;b.setPointerCapture(e.pointerId);seek(direction*10);seekDelay=setTimeout(()=>{if(!holding)return;b.classList.add('holding');seekTimer=setInterval(()=>seek(direction*3),100);},400);});['pointerup','pointercancel','lostpointercapture'].forEach(type=>b.addEventListener(type,endHold));b.addEventListener('click',e=>{if(e.detail===0)seek(direction*10);});}
 function renderList(){const list=$('chapterList');list.replaceChildren();state.tracks.forEach((t,i)=>{if(state.filter!=='all'&&String(t.book)!==state.filter)return;const row=document.createElement('button');row.className='chapter-row';row.setAttribute('aria-current',String(i===state.index));row.disabled=!state.key;const number=document.createElement('span');number.className='chapter-number';number.textContent=t.chapter||'·';const detail=document.createElement('span');detail.className='chapter-detail';const title=document.createElement('strong');title.textContent=t.title;const part=document.createElement('span');part.textContent=t.book?`Part ${t.book} · ${t.part}`:'Opening verse';detail.append(title,part);const meta=document.createElement('span');meta.className='chapter-meta';meta.textContent=fmt(t.duration)+(state.key&&!keyFor(t)?' · unlock':'');if(state.saved.has(t.id)){const check=document.createElement('span');check.className='cached-mark';check.textContent='OFFLINE';meta.append(check);}row.append(number,detail,meta);row.addEventListener('click',()=>{$('chapterDialog').close();load(i,true);});list.append(row);});}
 async function scanCache(){state.saved.clear();try{const cache=await caches.open(CACHE);const urls=new Set((await cache.keys()).map(r=>r.url));state.tracks.forEach(t=>{if(urls.has(urlFor(t)))state.saved.add(t.id);});}catch{}setMetadata();}
 async function saveTrack(t,signal){if(state.saved.has(t.id))return;const raw=await encrypted(t,(got,total)=>{$('downloadStatus').textContent=`${t.part} · ${t.title}: ${Math.min(100,Math.round(got/total*100))}%`;},signal);await verify(t,raw);if(signal?.aborted)throw new DOMException('Cancelled','AbortError');const cache=await caches.open(CACHE);await cache.put(urlFor(t),new Response(raw,{headers:{'Content-Type':'application/octet-stream','Content-Length':String(raw.length)}}));state.saved.add(t.id);setMetadata();}
 async function saveOffline(all){if(!state.key||state.saving||!track())return;state.saving=true;state.cancel=new AbortController();controlState();$('cancelSave').hidden=false;try{if(navigator.storage?.persist)await navigator.storage.persist();const selected=all?state.tracks:[track()];const need=selected.filter(t=>!state.saved.has(t.id)).reduce((n,t)=>n+t.bytes,0);if(navigator.storage?.estimate){const estimate=await navigator.storage.estimate();if(estimate.quota&&estimate.quota-(estimate.usage||0)<need+15e6)throw new Error('Not enough browser storage. Free space, then try again.');}for(const t of selected){if(state.cancel.signal.aborted)break;await saveTrack(t,state.cancel.signal);$('downloadStatus').textContent=`${state.saved.size} of ${state.tracks.length} chapters saved.`;}if(!state.cancel.signal.aborted){$('downloadStatus').textContent=all?'All available chapters are saved on this device.':'This chapter is saved on this device.';toast(all?'Available chapters saved for offline listening.':'Chapter saved offline.');}}
 catch(e){const msg=e.name==='AbortError'?'Offline saving cancelled. Completed chapters are kept.':e.name==='QuotaExceededError'?'Device storage is full. Completed chapters are kept.':e.message;$('downloadStatus').textContent=msg;toast(msg);}finally{state.saving=false;state.cancel=null;$('cancelSave').hidden=true;controlState();}}
 function show(id){$(id).showModal();}
 async function unlock(value){
  let code=value.trim(),preferred=new URLSearchParams(location.hash.slice(1)).get('t');
  if(code.includes('#')){const params=new URLSearchParams(code.slice(code.indexOf('#')+1));preferred=params.get('t')||preferred;code=params.get('k')||code;}
  if(!/^[A-Za-z0-9_-]{43}$/.test(code))throw new Error('Paste the complete 43-character unlock code or private link.');
  const key=await crypto.subtle.importKey('raw',b64(code),'AES-GCM',false,['decrypt']);let matched=null;
  for(const [id,file]of [['legacy','vault.json'],['sequential-v5','vault-v5.json']]){
   try{const response=await fetch(file);if(!response.ok)continue;const vault=await response.json(),proof=b64(vault.proof);const text=await crypto.subtle.decrypt({name:'AES-GCM',iv:proof.slice(0,12),additionalData:encode(AAD+'unlock')},key,proof.slice(12));if(new TextDecoder().decode(text)==='Taliesin private player'){matched=id;break;}}catch{}
  }
  if(!matched)throw new Error('That code does not match the available recordings. Keep both private links if you use the earlier and new chapters.');
  state.keys[matched]=key;state.key=key;
  try{await setting('keys-v5',state.keys);if(matched==='legacy')await setting('key',key);}catch{toast('Unlocked for this session. Keep your private link.');}
  $('unlockPanel').hidden=true;$('unlockCode').value='';chooseUnlocked(preferred);controlState();renderList();if(state.tracks.length)await load(state.index,false);
 }
 async function init(){if(!window.crypto?.subtle){status('Open this player over HTTPS in Safari.',true);return;}try{const r=await fetch('catalog.json',{cache:'no-cache'});if(!r.ok)throw new Error('Library catalog is not available.');state.catalog=await r.json();if(state.catalog.version!==2)throw new Error('Unrecognized catalog version.');state.tracks=state.catalog.tracks||[];if(!state.catalog.ready||state.tracks.length===0){$('chapterTitle').textContent='Recording not published';status('The player is installed, but the complete audio is not available yet.',true);return;}
 for(const t of state.tracks){if(!Number.isFinite(t.duration)||t.duration<=0||!Number.isSafeInteger(t.bytes)||t.bytes<28||!/^[a-f0-9]{64}$/.test(t.sha256))throw new Error('Invalid audio catalog.');urlFor(t);}
 try{const saved=JSON.parse(localStorage.getItem(NS+'-progress')||'{}');state.positions=saved.positions||{};state.index=Math.max(0,state.tracks.findIndex(t=>t.id===saved.last));}catch{}$('librarySummary').textContent=`${state.tracks.length} of ${state.catalog.expected_tracks||49} tracks published · ${fmt(state.catalog.total_duration)} · ${bytes(state.catalog.total_bytes)}`;$('encodingNote').textContent=state.catalog.encoding_note||'96 kbps stereo MP3 at the original 22,050 Hz source rate.';$('quality').textContent='96 kbps stereo · 1×';await scanCache();await restoreKeys();let code=new URLSearchParams(location.hash.slice(1)).get('k');if(code){try{await unlock(code);}catch(e){$('unlockPanel').hidden=false;$('unlockError').textContent=e.message;status('Unlock required.');}}else{if(state.key){chooseUnlocked(null);$('unlockPanel').hidden=true;await load(state.index,false);}else{$('unlockPanel').hidden=false;status('Unlock your private recording to listen.');}}controlState();
 if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js',{scope:'./'}).catch(()=>{});}
 }catch(e){$('chapterTitle').textContent='Library unavailable';status(e.message,true);}}
 $('play').addEventListener('click',()=>audio.paused?play():audio.pause());$('previous').addEventListener('click',()=>load(state.index-1,true,0));$('next').addEventListener('click',()=>load(state.index+1,true,0));hold('rewind',-1);hold('forward',1);window.addEventListener('blur',endHold);document.addEventListener('visibilitychange',()=>{if(document.hidden){endHold();savePosition(true);}});window.addEventListener('pagehide',()=>savePosition(true));
 $('seek').addEventListener('input',()=>{if(!state.loading&&state.current){audio.currentTime=Number($('seek').value);updateTime();}});$('seek').addEventListener('change',()=>savePosition(true));audio.addEventListener('timeupdate',()=>{updateTime();savePosition();});audio.addEventListener('play',updatePlay);audio.addEventListener('pause',()=>{updatePlay();savePosition(true);if(!state.loading&&state.current)status('Paused · your place is saved.');});audio.addEventListener('ended',()=>{savePosition(true);if(state.index<state.tracks.length-1)load(state.index+1,true,0);else{updatePlay();status(state.catalog.complete===false?'End of the available chapters. The remaining chapters have not been published yet.':'End of the book.');}});audio.addEventListener('ratechange',()=>{if(audio.playbackRate!==1)audio.playbackRate=1;});audio.addEventListener('error',()=>{if(!state.loading&&state.current)status('Playback stopped. Select the chapter to reload it.',true);});
 $('chaptersButton').addEventListener('click',()=>{renderList();show('chapterDialog');});$('menuButton').addEventListener('click',()=>show('menuDialog'));document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));document.querySelectorAll('[data-part]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.part;document.querySelectorAll('[data-part]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderList();}));
 $('unlockForm').addEventListener('submit',async e=>{e.preventDefault();$('unlockError').textContent='';try{await unlock($('unlockCode').value);}catch(error){$('unlockError').textContent=error.message;}});
 $('saveCurrent').addEventListener('click',()=>saveOffline(false));$('saveAll').addEventListener('click',()=>saveOffline(true));$('cancelSave').addEventListener('click',()=>state.cancel?.abort());$('restartChapter').addEventListener('click',()=>{audio.currentTime=0;savePosition(true);updateTime();$('menuDialog').close();});
 $('downloadCurrent').addEventListener('click',()=>{if(!state.current)return;const t=track(),a=document.createElement('a');a.href=state.current.url;a.download=`Taliesin_part_${t.book}_chapter_${String(t.chapter).padStart(2,'0')}.mp3`;document.body.append(a);a.click();a.remove();});
 $('clearOffline').addEventListener('click',async()=>{if(!confirm('Remove the saved audio from this device? Your listening position will stay saved.'))return;state.cancel?.abort();try{await caches.delete(CACHE);await caches.delete(CACHE+'-pieces');await scanCache();toast('Saved audio removed.');}catch{toast('Could not remove saved audio.');}});
 $('lockPlayer').addEventListener('click',async()=>{if(!confirm('Lock this device? Keep your private link or unlock code so you can return.'))return;savePosition(true);audio.pause();++state.token;state.cancel?.abort();state.key=null;state.keys={};state.loading=false;audio.removeAttribute('src');audio.load();release(state.current);release(state.next);state.current=state.next=null;try{await setting('key',undefined,true);await setting('keys-v5',undefined,true);}catch{}history.replaceState(null,'',location.pathname+location.search);$('unlockPanel').hidden=false;$('menuDialog').close();controlState();renderList();status('This device is locked.');});
 if(navigator.mediaSession){const handlers={play:()=>play(),pause:()=>audio.pause(),seekbackward:()=>seek(-10),seekforward:()=>seek(10),previoustrack:()=>load(state.index-1,true,0),nexttrack:()=>load(state.index+1,true,0),seekto:e=>{if(state.current){audio.currentTime=e.seekTime;updateTime();savePosition(true);}}};for(const [name,fn]of Object.entries(handlers)){try{navigator.mediaSession.setActionHandler(name,fn);}catch{}}}
 window.addEventListener('online',()=>{if(state.current)status('Connection restored.');});init();
})();
