"""Publication tests use generated bytes only, never the book or a real key."""
import json, os, tempfile
from pathlib import Path
from unittest.mock import patch
import publish_layered as pub
import layer_store as store


def main():
    with tempfile.TemporaryDirectory() as temp:
        root=Path(temp); out=root/'recordings'; player=root/'player'; player.mkdir()
        records=[]
        for number,tid in enumerate(pub.ORDER):
            raw=os.urandom(256); sha=store.digest(raw)
            src=out/'audio'/(tid+'-'+sha[:16])/'0000.bin'
            src.parent.mkdir(parents=True); src.write_bytes(raw)
            records.append({'id':tid,'segments':11057 if number==0 else 1,
                'verified':True,'full_decode_pass':True,'reassembly_byte_exact':True,
                'origin':'preserved_player' if number<10 else 'layered-1.0.0',
                'remote_readback_pass':number>=10,'duration':10.0,
                'bytes':len(raw),'sha256':sha,'chunks':[{'src':src.relative_to(root).as_posix(),
                    'bytes':len(raw),'sha256':sha}]})
        old={'version':2,'complete':False,'tracks':[dict(r) for r in records[:10]]}
        store.write(player/'catalog.json',old)
        with patch.object(pub,'ROOT',root),patch.object(pub,'OUT',out):
            catalog=pub.prepare(player,records)
            assert catalog['complete'] and len(catalog['tracks'])==49
            assert all(t['src'].startswith('audio-v2/') for t in catalog['tracks'])
            assert all(c['src'].startswith('audio-v2/') for t in catalog['tracks'] for c in t['chunks'])
            assert all(catalog['tracks'][i]['sha256']==records[i]['sha256'] for i in range(10))
            assert catalog['total_bytes']==49*256
            assert pub.prepare(player,records)==catalog
            try: pub.prepare(player,records[:-1])
            except ValueError: pass
            else: raise AssertionError('Incomplete collection accepted')
            bad=[dict(r) for r in records];bad[0]['sha256']='0'*64
            try: pub.prepare(player,bad)
            except ValueError: pass
            else: raise AssertionError('Existing recording replacement accepted')
            target=player/catalog['tracks'][0]['chunks'][0]['src'];target.write_bytes(b'bad')
            try: pub.prepare(player,records)
            except ValueError: pass
            else: raise AssertionError('Differing audio overwritten')
        print(json.dumps({'passed':True,'synthetic_bytes_only':True,'complete_collection_gate':True,
              'preserved_audio_identity':True,'safe_player_paths':True,'idempotent_publication':True,
              'reject_incomplete_collection':True,'reject_overwrite':True}))

if __name__=='__main__': main()
